Hotel_Management_System/ViewModels/GuestViewModel.cs
using Hotel_Management_System.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace Hotel_Management_System.ViewModels
{
    public class GuestViewModel
    {
        public int GuestId { get; set; }
        [Required, StringLength(50), Display(Name = "Guest Name")]
        public string Guest_Name { get; set; }
        [Required, StringLength(15)]
        public string Contact_Number { get; set; }
        [Required]
        public HttpPostedFileBase Picture { get; set; }
        [Required, StringLength(150)]
        public string Address { get; set; }
        [Required, StringLength(50)]
        public string City { get; set; }
        public virtual List<Reservation> Reservations { get; set; } = new List<Reservation>();
    }
}

Hotel_Management_System/Controllers/GuestsController.cs
using Hotel_Management_System.Models;
using Hotel_Management_System.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace Hotel_Management_System.Controllers
{
    [Authorize]
    public class GuestsController : Controller
    {
        private readonly HotelDbContext db = new HotelDbContext();
        // GET: Guests
        [AllowAnonymous]
        public async Task<ActionResult> Index(int pg = 1)
        {
            var data = await db.Guests.OrderBy(a => a.GuestId).ToPagedListAsync(pg, 5);
            return View(data);
        }
        public ActionResult Create()
        {

            GuestViewModel b = new GuestViewModel();
            b.Reservations.Add(new Reservation { });
            return View(b);
        }
        [HttpPost]
        public ActionResult Create(GuestViewModel data, string act = "")
        {
            if (act == "add")
            {
                data.Reservations.Add(new Reservation { });

                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                data.Reservations.RemoveAt(index);
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var b = new Guest
                    {
                        Guest_Name = data.Guest_Name,
                        Contact_Number = data.Contact_Number,
                        Address = data.Address,
                        City = data.City
                        
                    };
                    string ext = Path.GetExtension(data.Picture.FileName);
                    string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Server.MapPath("~/Pictures/") + fileName;
                    data.Picture.SaveAs(savePath);
                    b.Picture = fileName;
                    foreach (var l in data.Reservations)
                    {

                        b.Reservations.Add(l);
                    }
                    db.Guests.Add(b);
                    db.SaveChanges();
                }
            }
            ViewBag.Act = act;
            return PartialView("_CreatePartial", data);
        }
        public ActionResult Edit(int id)
        {
            var c = db.Guests
                
                  .FirstOrDefault(x => x.GuestId == id);
            var g = new GuestEditModel
            {
                GuestId=c.GuestId,
                Guest_Name = c.Guest_Name,
                Contact_Number = c.Contact_Number,
                Address = c.Address,
                City = c.City,
                Reservations = c.Reservations.ToList()

            };
            ViewData["CurrentPic"] = db.Guests.First(x => x.GuestId == id).Picture;
            return View(g);

        }
        [HttpPost]
        public ActionResult Edit(GuestEditModel data, string act = "")
        {
            if (act == "add")
            {
                data.Reservations.Add(new Reservation { });
            }

            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                data.Reservations.RemoveAt(index);
            }

            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var a = db.Guests.First(x => x.GuestId == data.GuestId);
                    a.Guest_Name = data.Guest_Name;
                    a.Contact_Number = data.Contact_Number;
                    a.Address = data.Address;
                    a.City = data.City;

                    if (data.Picture != null)
                    {
                        string ext = Path.GetExtension(data.Picture.FileName);
                        string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Server.MapPath("~/Pictures/") + fileName;
                        data.Picture.SaveAs(savePath);
                        a.Picture = fileName;
                    }
                    db.Reservations.RemoveRange(db.Reservations.Where(x => x.GuestId == data.GuestId).ToList());
                    foreach (var item in data.Reservations)
                    {
                        a.Reservations.Add(new Reservation
                        {
                            Reservation_Id = item.Reservation_Id,
                            Check_in_Date = item.Check_in_Date,
                            Check_out_Date = item.Check_out_Date,
                            Room_Type = item.Room_Type,
                            Room_Number = item.Room_Number,
                            IsCancelled = item.IsCancelled,

                        });
                    }

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            ViewData["CurrentPic"] = db.Guests.First(x => x.GuestId == data.GuestId).Picture;
            return View(data);

        }
        public ActionResult Delete(int id)
        {
            var guest = new Guest { GuestId = id };
            db.Entry(guest).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return Json(new { success = true, deleted = id });
        }
    }
}

Hotel_Management_System/Views/Guests/Create.cshtml
@model Hotel_Management_System.ViewModels.GuestViewModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="spnner" style="display:none">
            <div class="d-flex justify-content-end my-2">
                <div class="spinner-border text-warning" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
        <div class="alert alert-warning alert-dismissible fade show px-2" role="alert" id="successAlert" style="display:none">
            <strong>Success!</strong> Data saved successfully.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <div id="from-div">
            @using (Ajax.BeginForm("Create", "Guests", new { },
            new AjaxOptions
            {
                HttpMethod = "post",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "fields",
                LoadingElementId = "spnner",
                OnSuccess = "onSuccess"
            },
            new { enctype = "multipart/form-data", id = "frm" }))
            {

                <h3 class="mb-2">Add new Guest</h3>
                <div id="fields">
                    @Html.Partial("_CreatePartial", Model)
                </div>

                <div class="form-group row mb-1">

                    <div class="d-flex justify-content-between">
                        <button type="button" class="btn btn-secondary" name="act" id="back" value="back">Back to Index</button>
                        <button type="submit" class="btn btn-primary" name="act" value="insert">Save to database</button>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

@section styles
{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @*<script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        $(() => {
            $(".cd").datepicker({
                format: "yyyy-mm-dd"
            });
            $(".cd").val('');
        });
        $(() => {
            $(".od").datepicker({
                format: "yyyy-mm-dd"
            });
            $(".od").val('');
        });

        function onSuccess() {
            if ($("#server-task").val() == "insert") {
                $('input[type=text]').val('');
                $('select').val('');
                $("#successAlert").show(); 2023 - 08 - 24
            }
        }
    </script>
    <script>
        $(() => {
             $("#back").click(function () {
                var indexURL = "@Url.Action("Index", "Guests")";
                window.location.href = indexURL;
            });
        });
    </script>
}

Hotel_Management_System/Views/Guests/Edit.cshtml
@model Hotel_Management_System.ViewModels.GuestEditModel
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-8">
        <div id="spnner" style="display:none">
            <div class="d-flex justify-content-end my-2">
                <div class="spinner-border text-warning" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
        <div class="alert alert-warning alert-dismissible fade show px-2" role="alert" id="successAlert" style="display:none">
            <strong>Success!</strong> Data updated successfully.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        @using (Html.BeginForm("Edit", "Guests", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.GuestId)
            <h3 class="mb-2">Edit Book</h3>
            @Html.Partial("_EditPartial", Model)


            <div class="form-group row mb-1">
                <div class="d-flex justify-content-between">
                    <button type="button" class="btn btn-secondary" name="act" id="back" value="back">Back to Index</button>
                    <button type="submit" class="btn btn-primary" name="act" value="update">Save to database</button>
                </div>
            </div>

        }
    </div>

    <div class="col-4">
        <figure class="figure">
            <img src="~/Pictures/@ViewBag.CurrentPic" class="img-thumbnail" style="width: 175px; margin: 45px;" />
            <figcaption class="figure-caption text-center">Current Cover.</figcaption>
        </figure>

    </div>
</div>
@section styles
{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-icons-1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        $(() => {
            $(".cd").datepicker({
                format: "yyyy-mm-dd"
            });
            
        });
        $(() => {
            $(".od").datepicker({
                format: "yyyy-mm-dd"
            });
            
        });
    </script>
    <script>
        $(() => {
             $("#back").click(function () {
                var indexURL = "@Url.Action("Index", "Guests")";
                window.location.href = indexURL;
            });
        });
    </script>
}

Hotel_Management_System/Views/Guests/Index.cshtml
@model IEnumerable<Hotel_Management_System.Models.Guest>

@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-12">
        <h3 class="text-center">Booking List</h3>

        <div class="d-flex justify-content-end mb-1">
            <a href="@Url.Action("Create", "Guests")" class="btn btn-primary btn-sm">Create New Guest</a>
        </div>

        <table class="table table-bordered table-striped table-sm">
            <thead class="table-success">
                <tr>
                    <th></th>
                    <th></th>
                    <th>Guest Name</th>
                    <th>Contact_Number</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>...</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var t in Model)
                {
                    <tr style="vertical-align:middle" id="tr_@t.GuestId">
                        <td class="text-center">
                            <button type="button" id="show_@t.GuestId" class="btn btn-link btn-sm show" data-aid="@t.GuestId"><i class="bi bi-plus-square"></i></button>
                            <button type="button" id="hide_@t.GuestId" class="btn btn-link btn-sm hide" data-aid="@t.GuestId" style="display:none"><i class="bi bi-dash-square"></i></button>
                        </td>
                        <td class="text-center"><img src="~/Pictures/@t.Picture" class="img-thumbnail rounded" style="width:70px" /></td>
                        <td>@t.Guest_Name</td>
                        <td>@t.Contact_Number</td>
                        <td>@t.Address</td>
                        <td>@t.City</td>
                        <td>
                            <a title="Edit this item" href="@Url.Action("Edit", "Guests", new {id=t.GuestId})" class="btn btn-success btn-sm"><i class="bi bi-pencil"></i></a>
                            <button type="button" title="Delete this item" data-pk="@t.GuestId" href="@Url.Action("Delete", "Guests", new {id=t.GuestId})" class="btn btn-danger btn-sm del"><i class="bi bi-trash"></i></button>
                        </td>
                    </tr>
                    <tr style="display:none" id="p_@t.GuestId">
                        <td></td>
                        <td colspan="8">
                            <h4>List of Researvstion</h4>
                            <table class="table table-bordered table-sm">
                                <thead class="table-light">
                                    <tr>
                                        <th>Check In Date</th>
                                        <th>Check Out Date</th>
                                        <td>Room Type</td>
                                        <th>Room Number</th>
                                        <th>IsCancelled?</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var p in t.Reservations)
                                    {
                                        <tr>
                                            <td>@p.Check_in_Date.ToString("yyyy-MM-dd")</td>
                                            <td>@p.Check_out_Date.ToString("yyyy-MM-dd")</td>
                                            <td>@p.Room_Number</td>
                                            <td>@p.Room_Type</td>
                                            <td>@(p.IsCancelled ? "Yes" : "No")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="d-flex justify-content-end">
            @Html.PagedListPager((IPagedList)Model, pg => Url.Action("Index", new { pg = pg }), new PagedListRenderOptions
            {
                LiElementClasses = new string[] { "page-item" },
                PageClasses = new string[] { "page-link" }
            })
        </div>
    </div>
</div>
<div class="modal" tabindex="-1" id="delmodal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h5 class="modal-title">Delete Guest</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure to delete?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="btnyes">Yes</button>
            </div>
        </div>
    </div>
</div>
@section styles
{
    <link href="~/Content/bootstrap-icons-1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script>
        $(() => {
            $(".show").click(function () {
                var aid = $(this).data("aid");
                $(`#p_${aid}`).show();
                $(`#hide_${aid}`).show();
                $(this).hide();
            });
            $(".hide").click(function () {
                var aid = $(this).data("aid");
                $(`#p_${aid}`).hide();
                $(`#show_${aid}`).show();
                $(this).hide();
            })
        });
    </script>

    <script>
        var delModal;
        var delId = -1;
        $(() => {
            delModal = new bootstrap.Modal(document.getElementById('delmodal'));
            $(".del").click(function () {
                delModal.show();
                delId = $(this).data("pk");
                console.log(delId);
            });
            $("#btnyes").click(() => {
                $.ajax({
                    type: "post",
                    url: "/Guests/Delete/" + delId,
                    dataType: "json",
                    success: (r) => {
                        if (r.success == true) {
                            $("#tr_" + delId).remove();
                            $("#tr_p" + delId).remove();
                        }
                    }
                });
                delModal.hide();
            });
        })
    </script>
}

Hotel_Management_System/Views/Guests/_CreatePartial.cshtml
@model Hotel_Management_System.ViewModels.GuestViewModel

<input type="hidden" id="server-task" value="@ViewBag.Act" />

<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Guest_Name, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Guest_Name, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Guest_Name, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Contact_Number, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Contact_Number, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Contact_Number, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.City, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.City, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.City, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Address, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="col-12">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Check In Date</th>
                <th>Check Out Date</th>
                <td>Type of Roome</td>
                <th>Room Number</th>
                <th>IsCalcelled</th>
                <th>
                    <button type="submit" class="btn btn-secondary btn-sm add" name="act" value="add" formnovalidate><i class="bi bi-plus"></i></button>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Reservations.Count; i++)
            {
                <tr>
                    <td>
                        @Html.TextBoxFor(x => Model.Reservations[i].Check_in_Date, new { @class = "form-control cd", type="date" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Check_in_Date, "", new { @class = "text-danger" })

                    </td>
                    <td>
                        @Html.TextBoxFor(x => Model.Reservations[i].Check_out_Date, new { @class = "form-control od", type = "date" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Check_out_Date, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.EnumDropDownListFor(x => Model.Reservations[i].Room_Type, new { @class = "form-select" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Room_Type, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.TextBoxFor(x => Model.Reservations[i].Room_Number, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Room_Number, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.CheckBoxFor(x => Model.Reservations[i].IsCancelled, new { @class = "form-check" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].IsCancelled, "", new { @class = "text-danger" })
                    </td>

                    <th>
                        <button type="submit" class="btn btn-secondary btn-sm" name="act" value="remove_@i" formnovalidate><i class="bi bi-trash"></i></button>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

Hotel_Management_System/Views/Guests/_EditPartial.cshtml
@model Hotel_Management_System.ViewModels.GuestEditModel
<h3>Edit Guest</h3>
<input type="hidden" id="server-action" value="@ViewData["Act"]" />
@Html.HiddenFor(x => x.GuestId)
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Guest_Name, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Guest_Name, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Guest_Name, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Contact_Number, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Contact_Number, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Contact_Number, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.City, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.City, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.City, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Address, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="col-12">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Check In Date</th>
                <th>Check Out Date</th>
                <td>Type of Roome</td>
                <th>Room Number</th>
                <th>IsCalcelled</th>
                <th>
                    <button type="submit" class="btn btn-success btn-sm add" name="act" value="add" formnovalidate><i class="bi bi-plus"></i></button>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Reservations.Count; i++)
            {
                <tr>
                    <td>
                        @Html.TextBoxFor(x => Model.Reservations[i].Check_in_Date, new { @class = "form-control cd" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Check_in_Date, "", new { @class = "text-danger" })

                    </td>
                    <td>
                        @Html.TextBoxFor(x => Model.Reservations[i].Check_out_Date, new { @class = "form-control od" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Check_out_Date, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.EnumDropDownListFor(x => Model.Reservations[i].Room_Type, new { @class = "form-select" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Room_Type, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.TextBoxFor(x => Model.Reservations[i].Room_Number, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].Room_Number, "", new { @class = "text-danger" })
                    </td>
                    <td>
                        @Html.CheckBoxFor(x => Model.Reservations[i].IsCancelled, new { @class = "form-check" })
                        @Html.ValidationMessageFor(x => Model.Reservations[i].IsCancelled, "", new { @class = "text-danger" })
                    </td>
                    <th>
                        <button type="submit" class="btn btn-danger btn-sm" name="act" value="remove_@i" formnovalidate><i class="bi bi-trash"></i></button>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>